/***************/
/* SCRAPE URLS */
/***************/
const BASE_URL = "https://www.google.com/maps/search/";
const SUBURBS = [
  "Tarneit",
  "Wollert",
  "Rockbank",
  "Melton South",
  "Officer",
  "Clyde North",
  "Wyndham Vale",
  "Craigieburn",
  "Melbourne",
  "Sunbury",
  "Plumpton",
  "Cranbourne East",
  "Pakenham",
  "Truganina",
  "Mickleham",
  "Clyde",
  "Southbank",
  "Werribee",
  "Mernda",
  "Doreen",
  "Point Cook",
  "Footscray",
  "Epping",
  "Cranbourne West",
  "Greenvale",
  "Doncaster",
  "Cranbourne North",
  "Maribyrnong",
  "Preston",
  "Dandenong",
  "Richmond",
  "Docklands",
  "Cranbourne South",
  "Carlton",
  "Berwick",
  "West Melbourne",
  "Brunswick",
  "South Morang",
  "Keysborough",
  "Mount Waverley",
  "Reservoir",
  "Eynesbury",
  "North Melbourne",
  "Glen Waverley",
  "Northcote",
  "South Yarra",
  "Coburg",
  "Williams Landing",
  "Diggers Rest",
  "Bundoora",
  "Frankston",
  "Brookfield",
  "Mornington",
  "Croydon",
  "Abbotsford",
  "Mount Martha",
  "Officer South",
  "Brunswick East",
  "Camberwell",
  "Malvern East",
  "Kalkallo",
  "Noble Park",
  "Bentleigh East",
  "Port Melbourne",
  "Fitzroy North",
  "Clayton",
  "Mitcham",
  "St Kilda",
  "Alphington",
  "Box Hill",
  "Rye",
  "Glenroy",
  "Doncaster East",
  "Brighton",
  "Beaconsfield",
  "Junction Village",
  "Melton West",
  "Thornbury",
  "Highett",
  "Langwarrin",
  "Altona North",
  "Pascoe Vale",
  "Ringwood",
  "Mount Eliza",
  "Prahran",
  "Lilydale",
  "Kew",
  "Rosebud",
  "South Melbourne",
  "Wantirna South",
  "Hawthorn",
  "Collingwood",
  "Caulfield North",
  "Balwyn",
  "Cheltenham",
  "Lyndhurst",
  "Lalor",
  "Mulgrave",
  "Cranbourne",
  "Diamond Creek",
  "Toorak",
  "Keilor East",
  "Williamstown",
  "Cranbourne West",
  "Taylors Lakes",
  "Officer",
  "Hawthorn East",
  "Burwood",
  "North Melbourne",
  "Surrey Hills",
  "Beaumaris",
  "Wantirna",
  "Templestowe Lower",
  "Moonee Ponds",
  "Prahran",
  "Rosebud",
  "Brunswick West",
  "Hampton",
  "St Kilda East",
  "Blackburn",
  "Meadow Heights",
  "Diamond Creek",
  "Ascot Vale",
  "Fitzroy North",
  "Yarraville",
  "Taylors Hill",
  "Maribyrnong",
  "Sunshine North",
  "Mentone",
  "Clayton South",
  "Fawkner",
  "Docklands",
  "Caulfield South",
  "Ivanhoe",
  "Donvale",
  "Springvale South",
  "Altona North",
  "Vermont South",
  "Box Hill North",
  "Parkdale",
  "Nunawading",
  "Kilsyth",
  "Box Hill",
  "Avondale Heights",
  "Highett",
  "Newport",
  "Bulleen",
  "Kurunjang",
  "Bayswater",
  "Somerville",
  "Brunswick East",
  "Burwood East",
  "Chirnside Park",
  "Elsternwick",
  "Malvern",
  "West Footscray",
  "Vermont",
  "South Melbourne",
  "Blackburn South",
  "Broadmeadows",
  "Altona",
  "Forest Hill",
  "Rye",
  "Hallam",
  "Fitzroy",
  "Sandringham",
  "Keilor Downs",
  "Dingley Village",
  "Armadale",
  "Brookfield",
  "Sydenham",
  "Hastings",
  "Ringwood North",
  "Murrumbeena",
  "Oakleigh South",
  "Macleod",
  "Kensington",
  "Pascoe Vale South",
  "Maidstone",
  "Chadstone",
  "Sunshine",
  "Heathmont",
  "Mount Evelyn",
  "Montmorency",
  "Delahey",
  "Clyde North",
  "Ringwood East",
  "Doveton",
  "Cairnlea",
  "Mordialloc",
  "Oakleigh",
  "Williams Landing",
  "Braybrook",
  "Skye",
  "Bayswater North",
  "Collingwood",
  "Box Hill South",
  "Canterbury",
  "Beaconsfield",
  "Strathmore",
  "Rosanna",
  "Flemington",
  "Gladstone Park",
  "Ormond",
  "Lynbrook",
  "Melton",
  "Hughesdale",
  "Kings Park",
  "Ashburton",
  "Chelsea",
  "Healesville",
  "Croydon North",
  "Scoresby",
  "Abbotsford",
  "Cranbourne South",
  "Windsor",
  "Clarinda",
  "Airport West",
  "Lyndhurst",
  "Noble Park North",
  "Patterson Lakes",
  "Knoxfield",
  "Coburg North",
  "Derrimut",
  "Alphington",
  "Blackburn North",
  "Westmeadows",
  "Narre Warren North",
  "Lysterfield",
  "Ashwood",
  "Rockbank",
  "Heidelberg Heights",
  "West Melbourne",
  "Albert Park",
  "Aspendale",
  "Tullamarine",
  "Oakleigh East",
  "Viewbank",
  "Montrose",
  "Heidelberg",
  "Upwey",
  "Kew East",
  "Carlton North",
  "Keilor",
  "Eltham North",
  "Parkville",
  "Black Rock",
  "Bonbeach",
  "Fairfield",
  "Clifton Hill",
  "Dallas",
  "Aspendale Gardens",
  "Dromana",
  "Burnside",
  "Whittlesea",
  "Mckinnon",
  "Moorabbin",
  "Oak Park",
  "Edithvale",
  "Warrandyte",
  "Balaclava",
  "Caulfield",
  "Mont Albert North",
  "Albanvale",
  "Frankston North",
  "East Melbourne",
  "Plumpton",
  "Hadfield",
  "Campbellfield",
  "Eynesbury",
  "Rosebud West",
  "Heidelberg West",
  "Glen Huntly",
  "Mont Albert",
  "Emerald",
  "Niddrie",
  "Safety Beach",
  "Chelsea Heights",
  "Seddon",
  "Watsonia",
  "Hampton East",
  "Burnside Heights",
  "Warranwood",
  "Seabrook",
  "Croydon Hills",
  "Croydon South",
  "Lower Plenty",
  "Laverton",
  "Middle Park",
  "Crib Point",
  "Koo Wee Rup",
  "Albion",
  "Eaglemont",
  "Ivanhoe East",
  "Yallambie",
  "The Basin",
  "Wonga Park",
  "Carrum",
  "Aberfeldie",
  "Tyabb",
  "Belgrave",
  "Watsonia North",
  "Pearcedale",
  "St Kilda West",
  "Bittern",
  "Park Orchards",
  "Cockatoo",
  "Kingsville",
  "Kingsbury",
  "Sandhurst",
  "Upper Ferntree Gully",
  "Diggers Rest",
  "Hurstbridge",
  "Mccrae",
  "Briar Hill",
  "Attwood",
  "Monbulk",
  "Research",
  "Kealba",
  "Yarra Glen",
  "Wandin North",
  "Heatherton",
  "Plenty",
  "Travancore",
  "Spotswood",
  "Kilsyth South",
  "Coolaroo",
  "Balnarring",
  "Blairgowrie",
  "Saint Helena",
  "Ardeer",
  "Tootgarook",
  "Bunyip",
  "Seville",
  "Gembrook",
  "Notting Hill",
  "North Warrandyte",
  "Keilor Park",
  "Cremorne",
  "Yarra Junction",
  "Gowanbrae",
  "South Kingsville",
  "Williamstown North",
  "Launching Place",
  "Braeside",
  "Warburton",
  "Princes Hill",
  "Essendon North",
  "Officer South",
  "Sorrento",
  "Coldstream",
  "Jacana",
  "Woori Yallock",
  "Tecoma",
  "Caulfield East",
  "Junction Village",
  "Eumemmerring",
  "Olinda",
  "Millgrove",
  "Werribee South",
  "Baxter",
  "Beaconsfield Upper",
  "Huntingdale",
  "Brooklyn",
  "Clyde",
  "Harkaway",
  "Bellfield",
  "Seaholme",
  "Somers",
  "Shoreham",
  "Sassafras",
  "Langwarrin South",
  "Mickleham",
  "Ripponlea",
  "Blind Bight",
  "Dandenong South",
  "Belgrave South",
  "Keilor Lodge",
  "Wattle Glen",
  "Hoddles Creek",
  "Essendon West",
  "Panton Hill",
  "Garfield",
  "Devon Meadows",
  "Eden Park",
  "St Andrews",
  "Belgrave Heights",
  "Mount Dandenong",
  "Kallista",
  "Selby",
  "Lang Lang",
  "Toolern Vale",
  "Gardenvale",
  "Nar Nar Goon North",
  "Kalorama",
  "Kangaroo Ground",
  "Flinders",
  "Nar Nar Goon",
  "Tooradin",
  "Menzies Creek",
  "Badger Creek",
  "Bangholme",
  "Red Hill",
  "Lysterfield South",
  "Burnley",
  "Cottles Bridge",
  "St Andrews Beach",
  "Kooyong",
  "The Patch",
  "Portsea",
  "Ferny Creek",
  "Strathmore Heights",
  "Moorooduc",
  "Silvan",
  "Main Ridge",
  "Tynong",
  "Clematis",
  "Avonsleigh",
  "Dewhurst",
  "Fingal",
  "Chum Creek",
  "Mount Cottrell",
  "Wandin East",
  "Moorabbin Airport",
  "Pakenham Upper",
  "Tuerong",
  "Garfield North",
  "Gruyere",
  "Cape Schanck",
  "Lang Lang East",
  "Yellingbo",
  "Little River",
  "Beveridge",
  "Wesburn",
  "Christmas Hills",
  "Yarrambat",
  "Seville East",
  "Yan Yean",
  "Wildwood",
  "Catani",
  "Mount Burnett",
  "Cannons Creek",
  "Warneet",
  "Three Bridges",
  "Merricks North",
  "Yering",
  "Macclesfield",
  "Oaklands Junction",
  "Bulla",
  "Caldermeade",
  "Maryknoll",
  "Merricks",
  "Guys Hill",
  "Don Valley",
  "East Warburton",
  "Ravenhall",
  "Gilderoy",
  "Dixons Creek",
  "Modella",
  "Kinglake West",
  "Kalkallo",
  "Warrandyte South",
  "Arthurs Seat",
  "Cora Lynn",
  "Steels Creek",
  "Powelltown",
  "Boneo",
  "Sherbrooke",
  "Merricks Beach",
  "Fernshaw",
  "Keilor North",
  "Melbourne Airport",
  "Quandong",
  "Donnybrook",
  "Somerton",
  "Tottenham",
  "Cocoroc",
  "Mambourin",
  "Essendon Fields",
  "Hmas Cerberus",
  "Laverton North",
  "Tremont",
];
const generateUrls = (industries, suburbs = SUBURBS) => {
  let urls = [];
  industries.map((INDUSTRY) => {
    suburbs.map((SUBURB) => {
      urls.push(`${BASE_URL}${INDUSTRY}+${SUBURB}`);
    });
  });
  return urls;
};

module.exports = { generateUrls };
